{% set name = "myst-nb" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0e32990d1e2bb77b3803f2e6dbb24d01d89477719080d416576930d916bdd432

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils >=0.15,<0.18
    - importlib-metadata
    - ipython
    - ipywidgets >=7.0.0,<8
    - jupyter-cache ~=0.4.1
    - jupyter-sphinx ~=0.3.2
    - myst-parser ~=0.15.2
    - nbconvert >=5.6,<7
    - nbformat ~=5.0
    - python >=3.6
    - pyyaml
    - sphinx >=3.1,<5
    - sphinx-togglebutton ~=0.3.0

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.nb_glue
  commands:
    - pip check

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - mmcky
