{% set name = "myst-nb" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9077e42a1c6b441ea55078506f83555dda5d6c816ef4930841d71d239e3e0c5e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  entry_points:
    - mystnb-docutils-html = myst_nb.docutils_:cli_html
    - mystnb-docutils-html5 = myst_nb.docutils_:cli_html5
    - mystnb-docutils-latex = myst_nb.docutils_:cli_latex
    - mystnb-docutils-pseudoxml = myst_nb.docutils_:cli_pseudoxml
    - mystnb-docutils-xml = myst_nb.docutils_:cli_xml
    - mystnb-quickstart = myst_nb.cli:quickstart
    - mystnb-to-jupyter = myst_nb.cli:md_to_nb

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.4,<4
  run:
    - importlib-metadata
    - ipykernel
    - ipython
    - jupyter-cache >=0.5.0
    - myst-parser >=1.0.0
    - nbclient
    - nbformat >=5.0
    - python >=3.9
    - pyyaml
    - sphinx >=5
    - typing_extensions

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.ext.glue
  commands:
    - pip check
    - mystnb-docutils-html --help
    - mystnb-docutils-html5 --help
    - mystnb-docutils-latex --help
    - mystnb-docutils-pseudoxml --help
    - mystnb-docutils-xml --help
    - mystnb-quickstart --help
    - mystnb-to-jupyter --help

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - mmcky
    - conda-forge/jupyter-book
