{% set version = "0.13.0" %}

package:
  name: myst-nb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/myst-nb/myst-nb-{{ version }}.tar.gz
  sha256: 4666039f538abf32d6489f4caf912d505e8798a2709bcf7a7936823ca6b15810

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils >=0.15,<0.18
    - importlib_metadata
    - ipython
    - ipywidgets >=7.0.0,<8
    - jupyter-cache >=0.4.1,<0.5
    - jupyter-sphinx >=0.3.2,<0.4
    - myst-parser >=0.15.2,<0.16
    - nbconvert >=5.5,<7
    - nbformat >=5.0,<6
    - python >=3.6
    - pyyaml
    - sphinx >=3.1,<5
    - sphinx-togglebutton >=0.2.2,<0.3

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.nb_glue
  commands:
    - pip check

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - chrisjsewell
    - conda-forge/jupyter-book
