{% set name = "myst-nb" %}
{% set version = "0.17.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fdce98e47e7f020d8c0fb479bfbcc609a67b8c0ed79f0a50dd4e758a9142aaff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - flit-core >=3.4,<4
  run:
    - docutils >=0.15,<0.18
    - importlib-metadata
    - ipykernel
    - ipython
    - jupyter-cache >=0.5.0,<0.6.0
    - myst-parser >=0.17.2,<0.18.0
    - nbclient
    - nbformat >=5.0,<6
    - python >=3.7
    - pyyaml
    - sphinx >=3.5,<6
    - sphinx-togglebutton >=0.3.0,<0.4.0
    - typing-extensions

test:
  requires:
    - pip
  imports:
    - myst_nb
    - myst_nb.ext.glue
  commands:
    - pip check

about:
  home: https://github.com/executablebooks/MyST-NB
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A Jupyter Notebook Sphinx reader built on top of the MyST markdown parser.
  doc_url: https://myst-nb.readthedocs.io

extra:
  recipe-maintainers:
    - mmcky
    - chrisjsewell
    - conda-forge/jupyter-book
